sazzad/example_project/articles/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views


app_name = 'articles'
urlpatterns = [
    url(r'^$', views.ArticleListView.as_view(),
        name="list"),
    url(r'^~create$', views.ArticleCreateView.as_view(),
        name="create"),
    url(r'^(?P<slug>[\w-]+)$', views.ArticleDetailView.as_view(),
        name="details"),
    url(r'^(?P<slug>[\w-]+)/~update$', views.ArticleUpdateView.as_view(),
        name="update"),
    url(r'^(?P<slug>[\w-]+)/~delete$', views.ArticleDeleteView.as_view(),
        name="delete"),
]

sazzad/example_project/posts/urls.py
from guardian.compat import url

from posts import views

urlpatterns = [
    url(r'^$', views.post_list, name='posts_post_list'),
    url(r'^(?P<slug>[-\w]+)/$', views.post_detail, name='posts_post_detail'),
]

sazzad/example_project/urls.py
from guardian.compat import include, url, handler404, handler500
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout

__all__ = ['handler404', 'handler500']


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^article/', include('articles.urls', namespace='articles')),
    url(r'^', include('posts.urls')),
]

if 'grappelli' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^grappelli/', include('grappelli.urls')), ]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [url(r'^rosetta/', include('rosetta.urls')), ]

sazzad/example_project/articles/models.py
from __future__ import unicode_literals

from django.db import models
from guardian.compat import reverse


from guardian.models import GroupObjectPermissionBase, UserObjectPermissionBase


class Article(models.Model):
    title = models.CharField('title', max_length=64)
    slug = models.SlugField(max_length=64)
    content = models.TextField('content')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        permissions = (
            ('view_article', 'Can view article'),
        )
        get_latest_by = 'created_at'

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('articles:details', kwargs={'slug': self.slug})


class ArticleUserObjectPermission(UserObjectPermissionBase):
    content_object = models.ForeignKey(Article, on_delete=models.CASCADE)


class ArticleGroupObjectPermission(GroupObjectPermissionBase):
    content_object = models.ForeignKey(Article, on_delete=models.CASCADE)

sazzad/example_project/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime


class CustomUser(AbstractUser):
    birth_date = models.DateField(null=True, blank=True)


def get_custom_anon_user(User):
    return User(
        username='AnonymousUser',
        birth_date=datetime.date(1410, 7, 15),
    )

sazzad/example_project/posts/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField('title', max_length=64)
    slug = models.SlugField(max_length=64)
    content = models.TextField('content')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        permissions = (
            ('view_post', 'Can view post'),
        )
        get_latest_by = 'created_at'

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('posts_post_detail', (), {'slug': self.slug})

sazzad/example_project/articles/views.py
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from guardian.compat import reverse_lazy
from guardian.mixins import PermissionRequiredMixin, PermissionListMixin
from guardian.shortcuts import assign_perm
from articles.models import Article


class ArticleListView(PermissionListMixin, ListView):
    model = Article
    permission_required = ['view_article', ]


class ArticleDetailView(PermissionRequiredMixin, DetailView):
    model = Article
    permission_required = ['view_article']


class ArticleCreateView(PermissionRequiredMixin, CreateView):
    model = Article
    permission_object = None
    permission_required = ['articles.add_article']
    fields = ['title', 'slug', 'content']

    def form_valid(self, *args, **kwargs):
        resp = super(ArticleCreateView, self).form_valid(*args, **kwargs)
        assign_perm('view_article', self.request.user, self.object)
        assign_perm('change_article', self.request.user, self.object)
        assign_perm('delete_article', self.request.user, self.object)
        return resp


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    model = Article
    permission_required = ['view_article', 'change_article']
    fields = ['title', 'slug', 'content']


class ArticleDeleteView(PermissionRequiredMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('articles:list')
    permission_required = ['view_article', 'delete_article']

sazzad/example_project/posts/views.py
from django.contrib.auth.models import Group
from django.shortcuts import render_to_response, get_object_or_404
from django.views.generic import ListView
from django.template import RequestContext
from guardian.decorators import permission_required_or_403
from guardian.compat import get_user_model

from .models import Post

User = get_user_model()


class PostList(ListView):
    model = Post
    context_object_name = 'posts'

post_list = PostList.as_view()


@permission_required_or_403('posts.view_post', (Post, 'slug', 'slug'))
def post_detail(request, slug, **kwargs):
    data = {
        'post': get_object_or_404(Post, slug=slug),
        'users': User.objects.all(),
        'groups': Group.objects.all(),
    }
    return render_to_response(
        'posts/post_detail.html', data,
        RequestContext(request))

sazzad/example_project/articles/templates/articles/article_confirm_delete.html
{% extends "base.html" %}

{% load guardian_tags %}


{% block content %}
<p>Are you sure do you want to delete "<a href="{{object.get_absolute_url}}">{{object}}</a>"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Delete">
</form>
{% endblock %}

sazzad/example_project/articles/templates/articles/article_detail.html
{% extends "base.html" %}

{% load guardian_tags %}


{% block content %}
{% get_obj_perms request.user for object as 'object_perms' %}
<div class="row">
    <div class="span3">
        <a href="{% url "articles:list" %}">Back to article list</a>
    </div>


    <div class="span9">
    {% if "change_article" in object_perms %}
    <a href="{% url 'articles:update' slug=object.slug%}" class="btn btn-primary">Update</a>
    {% endif %}
    {% if "delete_article" in object_perms %}
    <a href="{% url 'articles:delete' slug=object.slug%}" class="btn btn-primary">Delete</a>
    {% endif %}
        <h1 name="{{ object.id }}">{{ object.title }}</h1>
        <h5>at {{ object.created_at }}</h5>
        <hr/>
        {{ object.content|safe }}
    </div>
</div>
{% endblock %}

sazzad/example_project/articles/templates/articles/article_form.html
{% extends "base.html" %}

{% load guardian_tags %}

{% block content %}
<div class="row">
    <div class="span12">
        <h1>{% if object %}
            <a href="{{ object.get_absolute_url }}" name="{{ object.id }}">Back to "{{ object.title }}"</a>
        {% else %}
            <a href="{% url "articles:list" %}">Back to article list</a>
        {% endif %}</h1>
        <form method="post">{% csrf_token %} {{ form.as_p }}
            <input type="submit" value="Save" class="btn btn-primary" />
        </form>
    </div>
</div>
{% endblock %}

sazzad/example_project/articles/templates/articles/article_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">

    <div class="span12">
        <div class="hero-unit">
            <h1>Articles</h1>
            <a href="{% url "articles:create" %}" class="btn btn-primary">Add article</a>
        </div>
    </div>
{% for object in object_list %}
    <div class="span3">
    </div>
    <div class="span9">
        <a href="{{object.get_absolute_url}}" name="{{ post.id }}"><h1>{{ object.title }}</h1></a>
        <h5>at {{ object.created_at }}</h5>
        <hr/>
        {{ object.content|safe }}
    </div>
{% endfor %}
</div>


{% endblock %}

sazzad/example_project/posts/templates/posts/post_detail.html
{% extends "base.html" %}

{% load guardian_tags %}

{% block content %}
<div class="row">
    <div class="span3">
        <a href="{% url "posts_post_list" %}">Back to posts list</a>
        <h4>User permissions</h4>
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
                {% for user in users %}
                {% comment %}
                Do NOT do this in your project - we are just showing all the
                permissions, however this span query for all users (at view)
                and for each user there is another query for the permissions
                (templatetag)
                {% endcomment %}
                <li class="nav-header">{{ user }}{% if user.is_superuser %} <span class="badge badge-info">admin</span>{% endif %}</li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url "admin:posts_post_permissions_manage_user" post.pk user.pk %}">Manage permissions</a></li>
                {% endif %}
                {% get_obj_perms user for post as "perms" %}
                {% for perm in perms %}
                <li>{{ perm }}</li>
                {% endfor %}
                {% endfor %}
            </ul>
        </div><!--/.well -->
    </div>
    
    <div class="span9">
        <h1 name="{{ post.id }}">{{ post.title }}</h1>
        <h5>at {{ post.created_at }}</h5>
        <hr/>
        {{ post.content|safe }}
    </div>
</div>

{% endblock %}

sazzad/example_project/posts/templates/posts/post_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">

    <div class="span3">
        <div class="well sidebar-nav">
            <ul class="nav nav-list">
                <li class="nav-header">Recent posts</li>
                {% for post in posts %}
                <li><a href="#{{ post.id }}">{{ post.title }}</a></li>
                {% endfor %}
            </ul>
        </div><!--/.well -->
    </div>

    <div class="span9">
        <div class="hero-unit">
            <h1>Posts</h1>
            <a href="{% url "admin:posts_post_add" %}" class="btn btn-primary">Add post</a>
        </div>
    </div>
{% for post in posts %}
    <div class="span3">
    </div>
    <div class="span9">
        <a href="{% url "posts_post_detail" post.slug %}" name="{{ post.id }}"><h1>{{ post.title }}</h1></a>
        <h5>at {{ post.created_at }}</h5>
        <hr/>
        {{ post.content|safe }}
    </div>
{% endfor %}
</div>


{% endblock %}

sazzad/example_project/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Guardian example{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
        <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" media="screen">
        <style>
            .container {
                margin-top: 60px;
            }
        </style>
    </head>
    <body>
        {% block navbar %}
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="#">Guardian example project v{{ version }}</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="{% url "posts_post_list" %}">Posts</a></li>
                            <li class="active"><a href="{% url "articles:list" %}">Articles</a></li>
                            <li><a href="https://github.com/django-guardian/django-guardian" target="_repo">Repository</a></li>
                            <li><a href="https://github.com/django-guardian/django-guardian/issues" target="_issues">Issue tracker</a></li>
                            <li><a href="https://django-guardian.readthedocs.io/en/latest/" target="_docs">Documentation</a></li>
                        </ul>
                        <p class="navbar-text pull-right">
                        {% if user.is_authenticated %}
                        Logged in as {{ user }}. <a href="{% url "logout" %}" class="navbar-link">Logout</a>
                        {% else %}
                        Not authenticated. Please use <a href="/admin/" class="navbar-link">admin</a> to login.
                        {% endif %}
                        </p>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        {% endblock %}
        <div class="container">
            {% block content %}
            <div class="row">
                <div class="span12">
                    <h1>Hello, world!</h1>
                </div>
            </div>
            {% endblock %}
        </div>
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    </body>
</html>

sazzad/example_project/templates/home.html
{% extends "base_1col.html" %}

{% block col-single-title %}Home{% endblock %}

{% block col-single-content %}
<div class="richblock">
    <h1>Pages</h1>
    <ul class="nav-vertical">
        {% for flatpage in flatpage_list %}
        <li><a href="{{ flatpage.url }}">{{ flatpage.title }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}