djp/cour/c/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url('^$',views.Te_index,name='index'),
    url('^create/',views.create_Te,name='create_te'),
    url('^update_te/(?P<id>[0-9]+)',views.create_save_data,name='update_te'),
    url('^createfromsave/',views.create_save_data,name='c_s_d'),
    url('^viewdetail/(?P<id>[0-9]+)',views.Te_single,name='show_detail'),
    url('^delete/(?P<id>[0-9]+)',views.delete_data,name='delete'),
    url('^update/(?P<id>[0-9]+)',views.form_update,name='update'),

]

djp/cour/c1/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$',views.C1_E_ListView.as_view(),name='index'),
    url(r'^create$',views.C1_E_CreateView.as_view(),name='create'),
    url(r'^detail/(?P<pk>[0-9]+)',views.C1_E_Delete.as_view(),name='delete'),
    url(r'^update/(?P<pk>[0-9]+)',views.C1_E_Update.as_view(),name='update'),
    url(r'^view/(?P<pk>[0-9]+)',views.C1_E_View.as_view(),name='view'),

    

]

djp/cour/cour/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^c/',include('c.urls',namespace='c')),
    url(r'^c1/',include('c1.urls',namespace='c1')),
    

]

djp/cour/c/models.py
from django.db import models

class Te(models.Model):
	name=models.CharField(max_length=100)
	address=models.CharField(max_length=200)
	age=models.IntegerField(default=30)

djp/cour/c1/models.py
from django.db import models

# Create your models here.

class C1_E(models.Model):
	name=models.CharField(max_length=100)
	address=models.CharField(max_length=200)
	roll=models.IntegerField(default=0)

djp/cour/c/forms.py
from django import forms

class Te_Model_Form(forms.Form):
	name=forms.CharField(max_length=200)
	address=forms.CharField(max_length=100)
	age=forms.IntegerField()

djp/cour/c/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Te
from .forms import Te_Model_Form
from django.core.urlresolvers import reverse_lazy,reverse
def create_Te(request):
	return render(request,'c/form_create.html',{'form':Te_Model_Form(),})

def create_save_data(request,id=None):
	data=request.POST
	form_data=Te_Model_Form(data)
	#return HttpResponse('<h2>'+ str(id) +'</h2>')



	a=Te()
	a.name=request.POST['name']
	a.address=request.POST['address']
	a.age=request.POST['age']

	if id is not None:
		a.id=id;
	a.save()
	return HttpResponseRedirect(reverse('c:index'))
	



def Te_index(request):
	data=Te.objects.order_by('id')
	return render(request,'c/index.html',{'data':data})
def Te_single(request,id):
	data=Te.objects.filter(id=id)
	return render(request,'c/index.html',{'data':data})
def delete_data(request,id):
	data=Te.objects.get(id=id)
	data.delete()
	return HttpResponseRedirect(reverse('c:index'))
def form_update(request,id):
	data=Te.objects.get(id=id)
	#return HttpResponse('<h2>'+ str(data.name) +'</h2>')
	form_class=Te_Model_Form(initial={'name':data.name,'address':data.address,'age':data.age})
	return render(request,'c/form_update.html',{'id':data.id,'form':form_class})

djp/cour/c1/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import C1_E
from django.core.urlresolvers import reverse,reverse_lazy
class C1_E_ListView(ListView):
	model=C1_E
	context_object_name='data'
	template_name='c1/index.html'
class C1_E_CreateView(CreateView):
	model=C1_E
	fields='__all__'
	template_name='c1/create.html'
	success_url=reverse_lazy('c1:index')

class C1_E_View(DetailView):
	model=C1_E
	template_name='c1/detail.html'
	context_object_name='data'
class C1_E_Delete(DeleteView):
	model=C1_E
	template_name='c1/confirm.html'
	success_url=reverse_lazy('c1:index')
class C1_E_Update(UpdateView):
	model=C1_E
	template_name='c1/create.html'
	success_url=reverse_lazy('c1:index')
	fields='__all__'

djp/cour/c/templates/c/form_create.html
<form method="post" action="{% url 'c:c_s_d'%}" >
	{% csrf_token %}
	{% for a in form %}
		{{a.label}}
		{{a}}<br/><br/>
		
	{% endfor%}
	<br/>
	<input type="submit" value="clicke me">

</form>

djp/cour/c/templates/c/form_update.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form method="post" action="{% url 'c:update_te' id %}" >
	{% csrf_token %}
	{% for a in form %}
		{{a.label}}
		{{a}}<br/><br/>
		
	{% endfor%}
	<br/>
	<input type="submit" value="click me">

</form>
</body>
</html>>

djp/cour/c/templates/c/index.html
<!DOCTYPE html>
<html>
<head>
	<title> THis is tile views</title>
</head>
<body>
		<a href="{% url 'c:create_te'%}">Ad new</a>
		{% if data %}
			<table border=1 style="border-collapse: collapse;"> 
				<tr><th>ID</th><th> Name</th><th>Address</th><th> Age</th><th>Action</th></tr>
			{% for a in data %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td> {{a.name}}</td>
					<td>{{a.address}}</td>
					<td> {{a.age }}</td>
					<td><a href="{% url 'c:show_detail' a.id %}">View</a>
					<a href="{% url 'c:delete' a.id %}">Delete</a>
					<a href="{% url 'c:update' a.id %}">Update</a></td>

				</tr>
			{% endfor %}
		</table>
		{% endif %}
</body>
</html>