sazzad/mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls',namespace='polls')),
    url(r'^polll1/', include('polll1.urls',namespace='polll1')),
    url(r'^articles/', include('articles.urls',namespace='articles')),
    #url(r'^', include('snippet.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sazzad/mysite/polls/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^create/',views.create,name='create'),
    url(r'^view/(?P<pk>[0-9]+)$',views.view,name='view'),
    url(r'^update/(?P<pk>[0-9]+)$',views.update,name='update'),
    url(r'^delete/(?P<pk>\d+)$',views.delete,name='delete'),
    url(r'^createview/',views.QuestionListView.as_view(),name='createview'),
    url(r'^updateview/(?P<pk>\d+)$',views.EditQuestionView.as_view(),name='updateview'),
    url(r'^detailview/(?P<pk>\d+)$',views.QuestinDetailView.as_view(),name='detailview'),
    url(r'^deleteview/(?P<pk>\d+)$',views.QuestionDeleteView.as_view(),name='deleteview'),
    url(r'^createpublisher/',views.PublisherCreateView.as_view(),name='publishcreate'),
    url(r'^updatepublisher/(?P<pk>[0-9]+)$',views.PublisherUpdateView.as_view(),name='publishupdate'),
    url(r'^deletepublisher/(?P<pk>[0-9]+)$',views.PublisherDeleteView.as_view(),name='publishdelete'),
    url(r'^listpublisher/$',views.PublishListView.as_view(),name='listpublisher'),
    url(r'^formcheck/$',views.Contant.as_view(),name='formcheck'),
    url(r'^formtest$',views.formsettest,name='formtest'),
    url(r'^formtesttest$',views.saveMyspecialFuction,name='formtesttest'),



]

sazzad/mysite/polls/models.py
from django.db import models
from django.urls import reverse,reverse_lazy

class Question(models.Model):
    question_text=models.CharField(max_length=2000)
    pub_date=models.DateTimeField('date of published')
class Choice(models.Model):
    questoin_id=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    vote=models.IntegerField(default=0)
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()
    def get_absolute_url(self):
    	return reverse('polls:listpublisher')


    class Meta:
        ordering = ["-name"]

    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Author(models.Model):
    salutation = models.CharField(max_length=10)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    #headshot = models.ImageField(upload_to='author_headshots')

    def __str__(self):              # __unicode__ on Python 2
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()
class Sazzad(models.Model):
	name=models.CharField(max_length=100)
	def get_absolute_url(self):
		return reverse('polls:listpublisher')

class SaveMyFirstName(models.Model):
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=30)
    fullnam=models.CharField(max_length=30)

sazzad/mysite/polls/forms.py
from django.forms import ModelForm,formset_factory
from django import forms
from .models import Question,Publisher,SaveMyFirstName
class CreateQuestionForm(ModelForm):
    class Meta:
        model=Question
        fields='__all__'
        exclude=['pub_date',]
class PublisherFormCreate(ModelForm):
	class Meta:
		model=Publisher
		fields='__all__'
class PlayingWithForm(forms.Form):
	question_text=forms.CharField(max_length=100)
class ContactForm(forms.Form):
	subject=forms.CharField(max_length=100)
	message=forms.CharField(widget=forms.Textarea)
	sender=forms.EmailField()
	cc_myself=forms.BooleanField(required=False)
class QuestionForm(forms.Form):
	name=forms.CharField(max_length=40)
	
class saveMyForm(ModelForm):
	class Meta:
		model=SaveMyFirstName
		fields='__all__'

sazzad/mysite/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from django.forms import formset_factory,modelformset_factory
from django.urls import reverse_lazy,reverse
from .models import Question,Choice,Publisher,Book,Sazzad,Author,SaveMyFirstName
from .forms import CreateQuestionForm,PublisherFormCreate,ContactForm,PlayingWithForm,QuestionForm,saveMyForm
from django.utils import timezone
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView,FormView,DeleteView,FormView
def index(request):
    data=Question.objects.all()
    template=loader.get_template('polls/index.html')
    return HttpResponse(template.render({'data':data},request))
def create(request):
    if request.method=='POST':
        a=CreateQuestionForm(request.POST)
        b=a.save(commit=False)
        b.pub_date=timezone.now()
        data = Question.objects.all()
        b.save()
    else:
        a=CreateQuestionForm()
        template=loader.get_template('polls/createform.html')
        return HttpResponse(template.render({'a':a, },request))
    return render(request,'polls/index.html',{'data':data})
def view(request,pk):
    a=Question.objects.get(pk=pk)
    context={'singledata':a}
    return render(request,'polls/index.html',context)
def update(request,pk):
    if request.method=='POST':
        a=CreateQuestionForm(request.POST)
        b=a.save(commit=False)
        b.pub_date=timezone.now()
        b.id=pk
        b.save()
        data = Question.objects.all()

        return render(request, 'polls/index.html', {'data': data})

    else:
        #using the existing create form
        data=Question.objects.get(pk=pk)
        return render(request,'polls/edit.html',{'data':data})
def delete(request,pk):
    a=Question.objects.filter(pk=pk)
    a.delete()
    data=Question.objects.all()
    return render(request, 'polls/index.html', {'data': data})

class QuestionListView(CreateView):
    model = Question
    context_object_name = 'fineform'
    template_name = 'polls/createview.html'
    fields = ['question_text',]


class EditQuestionView(UpdateView):
    model = Question
    fields = ['question_text',]
    template_name ='polls/updateview.html'
    context_object_name = 'update'
    success_url = reverse_lazy('polls:index')
class QuestinDetailView(DetailView):
    model = Question
    context_object_name = 'singledata'
    template_name = 'polls/index.html'
class QuestionDeleteView(DeleteView):
    model = Question
    template_name = 'polls/delete.html'
    context_object_name = 'delete'
    success_url='../'
class PublisherCreateView(CreateView):
    model=Publisher
    fields='__all__'
    template_name='polls/publish.html'
class PublisherUpdateView(UpdateView):
    model=Publisher
    fields='__all__'
    template_name='polls/publish.html'

class PublisherDeleteView(DeleteView):
    model=Publisher
    context_object_name='form'
    success_url=reverse_lazy('polls:listpublisher')
class PublishListView(ListView):
    model=Publisher
    template_name='polls/pushlish_list.html'
    context_object_name='publisher'

class SazzadSpecialCheck(FormView):
    '''This class is build for testing the form_valid mehtod
    and its functionality'''
    template_name='polls/check.html'
    form_class=PublisherFormCreate
    success_url=reverse_lazy('polls:listpublisher')
    def form_valid(self,form):
        form.save()
        return super(SazzadSpecialCheck,self).form_valid(form)

class Contant(FormView):
    template_name='polls/contactform.html'
    form_class=ContactForm
    context_object_name="formal"
def UseSameFormForCreateAndUpdate(request,id):
    '''this was created for checking something'''
    pass
def functiontest(request):
    if request.method=='POST':
        a=Question()
        a.question_text=request.POST['question_text']
        a.pub_date=timezone.now()
        a.save()
        return HttpResponseRedirect(reverse('polls:index'))
    else:
        a=PlayingWithForm()
        return render(request,'polls/test.html',{'form':a})
def formsettest(request):
    a=formset_factory(CreateQuestionForm,extra=8,max_num=10)
    b=a(initial=[{'question_text':'what is your nnnnname?? ',}])
    return render(request,'polls/formset.html',{'context':b,})

def QuestionFormView(request):
    multiquestionform=modelform_factory(Author,fields=['salutation','name','email'])
    if request.method=='POST':
        instances=multiquestionform(request.POST,request.FILES)
        
        if instances.is_valid():
            instances.save()
            return HttpResponseRedirect(reverse('polls:index'))


    objectform=multiquestionform()

    return render(request,'polls/test.html',{'form':objectform})
def saveMyspecialFuction(request):
    ob=modelformset_factory(SaveMyFirstName,fields='__all__',extra=3,max_num=5)
    if request.method=='POST':
        objct=ob(request.POST,request.FILES)
        objects=objct.save(commit=False)
        s=' this is  mr khan '
        for a in objects:
            a.save()


        return HttpResponse('<h2>'+s+'</h2>')
    else:
        objectform=ob()
        return render(request,'polls/test.html',{'form':objectform})

sazzad/mysite/polls/templates/polls/check.html
<form method="post" action="">
	{% csrf_token %}
	{{form}}
	<input type="submit" name="">
	
</form>

sazzad/mysite/polls/templates/polls/contactform.html
<h2> This form is comming here</h2>
{{ form.as_table }}
<h2>This is for paragraph format</h2>
{{ form.as_p }}
<h2> this is List format</h2>
{{ form.as_ul }} 

<br/><br/>
<form action="" method="post">
{% for field in form %}
	{{ field.label_tag }}<br/>
	{{ field.label }}
	{{field}}
	
{% endfor %}
<input type="submit" value="submit">
</form>

<h2>This is another example</h2>
{{formal}}

sazzad/mysite/polls/templates/polls/createform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url 'polls:create' %}">
    {% csrf_token %}
    {{ a }}

    <input type="submit"/>
</form>
</body>
</html>

sazzad/mysite/polls/templates/polls/createview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2> this is create form</h2>
    <form method="post" action="{% url 'polls:create' %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
    </form>





</body>
</html>

sazzad/mysite/polls/templates/polls/delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ delete }}"?</p>
    <input type="submit" value="Confirm" />
</form>
<h2> asfasd{{ form.instance.id}}</h2>

sazzad/mysite/polls/templates/polls/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url 'polls:update' data.id%}">
    {% csrf_token %}
    <input type="text" name="question_text" value="{{data.question_text}}">
    <input type="submit">
</form>
</body>
</html>

sazzad/mysite/polls/templates/polls/formset.html
<form action="{% url 'polls:formtesttest'%}" method="post">
{% for a in context %}
	{% csrf_token %}
	{{ a.as_p }}
	

{% endfor %}
<input type="submit" value="click me">
</form>

sazzad/mysite/polls/templates/polls/index.html
{% extends 'base1.html' %}

sazzad/mysite/polls/templates/polls/publish.html
<form method="post" action="">
	{% csrf_token %}
	{{form}}
	<input type="submit" value="click me">
</form>

sazzad/mysite/polls/templates/polls/publisher_confirm_delete.html
<form method="post" action="">
	{% csrf_token%}
	<input type="submit"/>
</form>

sazzad/mysite/polls/templates/polls/publisher_list.html
<a href="{% url 'polls:publishcreate'%}">Create New </a>
{% block content %}
    <h2>Publishers</h2>
    <ul>
        {% for publisher in publisher %}
            <li>{{ publisher.name }}</li>
            <a href="{% url 'polls:publishupdate' publisher.id %}">Update</a><a href="{% url 'polls:publishdelete' publisher.id %}">Delete</a>

        {% endfor %}
    </ul>
{% endblock %}

sazzad/mysite/polls/templates/polls/test.html
{% if form %}
<form action="{% url 'polls:formtesttest'%}" method='post'>
	{% csrf_token %}
	{{form.management_form}}
	{% for frm in form%}
		{{frm}}
		<br/>
	{%  endfor%}
	<input type="submit" value="clickme">
</form>

{% endif %}
{% if abs %}
	{{ abs }}
{% endif%}

sazzad/mysite/polls/templates/polls/updateview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
      <form method="post" action="{% url 'polls:update' form.instance.id %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
    </form>
      <h2>{{form.instance.id}}</h2>
</body>
</html>