djp/course/check/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	 url(r'^$',views.index,name='index'),
	 url(r'^create$',views.createformclass,name='createform'),
	 url(r'^createsubmit$',views.create_form_data_save,name='create'),
	 url(r'^singleview/(?P<id>[0-9]+)$',views.single_document_shortcut,name='singleview'),
	 url(r'^update/(?P<id>[0-9]+)$',views.update,name='update'),
	 url(r'^updateform/(?P<id>[0-9]+)$',views.updateform,name='updateform'),
	 url(r'^deletedata/(?P<id>[0-9]+)$',views.deletedata,name='delete'),


]

djp/course/course/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^teacher/',include('teacher.urls',namespace='teacher')),
    url(r'^check/',include('check.urls',namespace='check')),
]

djp/course/teacher/urls.py
from django.conf.urls import url,include
from . import view1,views

urlpatterns = [
    url(r'^create$',view1.TeacherCreateView.as_view(),name='create'),
    url(r'^formsubmit',views.formdata,name='formdata'),
    url(r'^singleview/(?P<id>[0-9]+)',views.single_view,name='singleview'),
    url(r'^update/(?P<pk>[0-9]+)',view1.TeacherUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>[0-9]+)',view1.TeacherDeleteView.as_view(),name='delete'),
    url(r'^updateform/(?P<id>[0-9]+)',views.formdata_update,name='updateform'),
    url(r'^$',view1.TeacherListView.as_view(),name='index1'),
    url(r'^showteacherdetail/(?P<pk>[0-9]+)$',view1.TeacherDetailView.as_view(),name='detail'),
]

djp/course/check/models.py
from django.db import models


class Check(models.Model):
	name=models.CharField(max_length=100)
	address=models.CharField(max_length=100)
	roll=models.CharField(max_length=200)
	age=models.IntegerField(default=50)
	
		
class CheckSub(models.Model):
	check_id=models.ForeignKey(Check,on_delete=models.CASCADE)
	name=models.CharField(max_length=300)

djp/course/teacher/models.py
from django.db import models


class Teacher(models.Model):
	name=models.CharField(max_length=50)
	title=models.CharField(max_length=50)
	age=models.IntegerField(default=30)
	major=models.CharField(max_length=30)

djp/course/check/forms.py
from django import forms

class Check(forms.Form):
	name=forms.CharField(max_length=200)
	address=forms.CharField(max_length=200)
	roll=forms.CharField(max_length=200)
	age=forms.IntegerField()

djp/course/check/views.py
from django.shortcuts import render,get_object_or_404,get_list_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import Check,CheckSub
from .forms import Check as Ch
from django.core.urlresolvers import reverse
def index(request):
	context={
	'data':Check.objects.all().order_by('id')
	}
	template=loader.get_template('check/index.html')

	return HttpResponse(template.render(context,request))

def create(request):
	data=Check()
	data.name=request.POST['name']
	data.address=request.POST['address']
	data.age=request.POST['age']
	data.roll=request.POST['roll']

	data.save()
	return HttpResponseRedirect(reverse('check:index'))
def createform(request):
	template=loader.get_template('check/createform.html')
	return HttpResponse(template.render({},request))
def singleview(request,id):
	context={
	'data':Check.objects.filter(pk=id),
	'singleview':True,
	}
	template=loader.get_template('check/index.html')

	return HttpResponse(template.render(context,request))

def update(request,id):
	context={
	'data':Check.objects.get(pk=id),
	}
	template=loader.get_template('check/updateform.html')
	return HttpResponse(template.render(context,request))

def updateform(request,id):
	data=Check()
	data.id=id;
	data.name=request.POST['name']
	data.address=request.POST['address']
	data.age=request.POST['age']
	data.roll=request.POST['roll']

	data.save()
	return HttpResponseRedirect(reverse('check:index'))
def deletedata(request,id):
	Check.objects.get(pk=id).delete()
	return HttpResponseRedirect(reverse('check:index'))

def single_document_shortcut(request,id):
	data=get_list_or_404(Check,pk=id)
	return render(request,'check/index.html',{'data':data,'singleview':True,})


def createformclass(request):
	form_class=Ch(initial={'name':'sazzad','age':67,})
	
	return render(request,'check/createform.html',{'form':form_class,})


def create_form_data_save(request):
	data=request.POST
	form_class=Ch(data)
	s=""
	if form_class.is_valid():
		q=form_class.clean()
		p=Check()
		p.name=q['name']
		p.address=q['address']
		p.roll=q['roll']
		p.age=q['age']
		p.save()

	return HttpResponseRedirect(reverse('check:index'))

djp/course/teacher/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import Teacher
from django.core.urlresolvers import reverse

def index(request):
	template=loader.get_template('teacher/index.html')
	context={
	'data':Teacher.objects.all()
	}
	return HttpResponse(template.render(context,request))
	
def create(request):
	template=loader.get_template('teacher/form.html')
	return HttpResponse(template.render({},request))
def formdata(request):

	data=Teacher()
	data.name=request.POST['name']
	data.title=request.POST['title']

	data.major=request.POST['major']

	data.save()
	return HttpResponseRedirect(reverse('teacher:index'))

def single_view(request,id):
	data=Teacher.objects.filter(pk=id)
	context={
	'data':data
	}
	template=loader.get_template('teacher/index.html')
	return HttpResponse(template.render(context,request))

def update(request,id):
	data=Teacher.objects.get(pk=id)
	context={
	'form':data
	}
	template=loader.get_template('teacher/form.html')
	return HttpResponse(template.render(context,request))
def formdata_update(request,id):
	a=Teacher()
	a.id=id
	a.name=request.POST['name']
	a.title=request.POST['title']
	a.major=request.POST['major']
	a.save();
	return HttpResponseRedirect(reverse('teacher:index'))

def delete_data(request,id):
	a=Teacher.objects.get(pk=id)
	a.delete()
	return HttpResponseRedirect(reverse('teacher:index'))

djp/course/check/templates/check/createform.html
<!DOCTYPE html>
<html>
<head>
	<title> Create From</title>
</head>
<body>
	{% if not form %}
	<form method="post" action="{% url 'check:create' %}">
		{% csrf_token %}
		<label>Name</label>
		<input type="text" name="name"><br/><br/>
		<label> Adress</label>
		<input type="text" name="address"><br/><br/>
		<label> Age</label>
		<input type="number" name="age"><br/><br/>
		<label>Roll</label>
		<input type="text" name="roll"><br/><br/>
		<input type="submit" value="click me">
	{% elif form %}
		<form method="post" action="{% url 'check:create' %}">
			{% csrf_token %}
			{% for a in form %}
				{{a.label}}
				{{a}}<br/><br/>
			{% endfor%}
			<input type="submit" name="">
			
		</form>
	{% endif %}


	</form>

</body>
</html>

djp/course/check/templates/check/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title> This is check page</title>
	// rel='stylesheet' diya foroj
	<link  rel="stylesheet" type="text/css" href="{% static 'check/index.css' %}" />
</head>
<body>


	<a href ="{% url 'check:createform' %}"> Add New </a>
		{% if data %}
			<table border="1px" style="border-collapse: collapse;" >
				<tr>
					<th>ID</th>
					<th> Name</th>
					<th>Adress</th>
					<th>Roll</th>
					<th>Age</th>
					<th> ACTION </th>
				</tr>
			
			{% for a in data %}
			<tr>
				<td>{{ forloop.counter }}</td>
				<td>{{a.name}}</td>
				<td>{{a.address}}</td>
				<td>{{a.roll}}</td>
				<td>{{a.age}}</td>
				<td> 
				<a href="{% url 'check:singleview' a.id %}"> View</a>
					<a href="{% url 'check:update' a.id %}">Update </a>
					<a href="{% url 'check:delete' a.id %}">Delete</a>

				</td>

			</tr>
				

			{% endfor %}
		</table>
		{% endif %}

		{% if singleview %}
			<h2> This is showing Detail of single id </h2>
			<a href="{% url 'check:index' %}"> Go home</a>
		{% endif %}
</body>
</html>

djp/course/check/templates/check/updateform.html
<!DOCTYPE html>
<html>
<head>
	<title> Update From</title>
</head>
<body>
	<form method="post" action="{% url 'check:updateform' data.id %}">
		{% csrf_token %}
		<label>Name</label>
		<input type="text" name="name" value="{{ data.name}}"><br/><br/>
		<label> Adress</label>
		<input type="text" name="address" value="{{ data.address}}"><br/><br/>
		<label> Age</label>
		<input type="number" name="age" value="{{ data.age}}"><br/><br/>
		<label>Roll</label>
		<input type="text" name="roll" value="{{ data.roll}}"><br/><br/>
		<input type="submit" value="click me">


	</form>

</body>
</html>

djp/course/teacher/templates/teacher/confirm.html
<form method="post">
	{% csrf_token %}
	{{form}}
	<input type="submit">
</form>

djp/course/teacher/templates/teacher/create_form_view.html
<!DOCTYPE html>
<html>
<head>
	<title> THis is Create View </title>
</head>
<body>
	<form method="post" >
		{% csrf_token %}
		{% for a in form %}
			{{a.label}}<br/>{{a}}<br/><br/>
		{% endfor %}
		<input type="submit">
		
	</form>
</body>
</html>

djp/course/teacher/templates/teacher/form.html
<!DOCTYPE html>
<html>
<head>
	<title>THis is form </title>
</head>
<body>
	{% if not form %}
	<form action="{% url 'teacher:formdata' %}" method="post">
		{% csrf_token %}
		<label> Name</label>
		<input type="text" name="name"><br/>
		<label>Title</label>
		<input type="text" name="title"><br/>
		<label> Age</label>
		<input type="number" name="age"><br/>
		<label> Major</label>
		<input type="text" name="major">
		<input type="submit" value="clickme">

	</form>
	


	{% elif form %}
		
		<form action="{% url 'teacher:updateform' form.id %}" method="post">
		{% csrf_token %}
		<label> Name</label>
		<input type="text" name="name" value="{{form.name}}"><br/>
		<label>Title</label>
		<input type="text" name="title"  value="{{form.title}}"><br/>
		<label> Age</label>
		<input type="number" name="age"  value="{{form.age}}"><br/>
		<label> Major</label>
		<input type="text" name="major"  value="{{form.major}}"><br/>
		<input type="submit" value="clickme">

	</form>
	{% endif %}

	

</body>
</html>

djp/course/teacher/templates/teacher/index.html
<!DOCTYPE html>
<html>
<head>
	<title>THis is title page </title>
</head>
<body>
	<h2>Hello you are in template now so go first</h2>

	<a href="{% url 'teacher:create'%}">Add new</a>
		{% if flag %}
			{% if data %}

					<table border=1 style='border-collapse:collapse;'>
						<tr>
							<th> Id </th>
							<th> Name </th>
							<th> Title </th>
							<th> age </th>
							<th> Major </th>
							<th> Action</th>
						</tr>
						{% for a in data%}

						<tr>
							<td>{{a.id}}</td>
							<td> {{a.name}}</td>
							<td> {{a.title}}</td>
							<td> {{a.age}}</td>
							<td> {{a.major}} </td>
							<td>
								<a href="{% url 'teacher:detail' a.id %}">View</a>
								<a href="{% url 'teacher:update' a.id %}">Update</a>
								<a href="{% url 'teacher:delete' a.id %}">Delete</a>


							</td>



						</tr>
						{% endfor%}
					</table>
					
			{% endif %}
		{% elif not flag%}
			<table border=1 style='border-collapse:collapse;'>
						<tr>
							<th> Id </th>
							<th> Name </th>
							<th> Title </th>
							<th> age </th>
							<th> Major </th>
							<th> Action</th>
						</tr>

						<tr>
							<td>{{data.id}}</td>
							<td> {{data.name}}</td>
							<td> {{data.title}}</td>
							<td> {{data.age}}</td>
							<td> {{data.major}} </td>
							<td>
								<a href="{% url 'teacher:detail' data.id %}">View</a>
								<a href="{% url 'teacher:update' data.id %}">Update</a>
								<a href="{% url 'teacher:delete' data.id %}">Delete</a>


							</td>



						</tr>
				</table>
		{% endif %}


		
			


</body>
</html>